version: '3.8'

services:
  ## APP SERVER
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - laravel-docker:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db

  ## MYSQL DATABASE
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  ## PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db

volumes:
  laravel-docker:
  mysql_data:
