name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.36
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_ROOT_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP and Node.js Dependencies
        run: |
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Install Laravel Breeze
        run: |
          composer require laravel/breeze --dev --no-ansi --no-interaction
          php artisan breeze:install blade --no-interaction

      - name: Build the Project for Production
        run: |
          npm run build
          export LARAVEL_BYPASS_ENV_CHECK=1

      - name: Generate key
        run: php artisan key:generate --no-interaction

      - name: Generate storage link
        run: php artisan storage:link --no-interaction

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Wait for MySQL to be ready
        run: sleep 30

      - name: Create database user and grant privileges
        env:
          MYSQL_PWD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          mysql -u root -h 127.0.0.1 -e "CREATE USER 'hpqjihel_user'@'%' IDENTIFIED BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
          mysql -u root -h 127.0.0.1 -e "GRANT ALL PRIVILEGES ON ${{ secrets.MYSQL_ROOT_DATABASE }}.* TO '${{ secrets.MYSQL_ROOT_USER }}'@'%';"
          mysql -u root -h 127.0.0.1 -e "FLUSH PRIVILEGES;"

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: ${{ secrets.MYSQL_ROOT_DATABASE }}
          DB_USERNAME: ${{ secrets.MYSQL_ROOT_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: php artisan migrate --force --no-interaction

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: ${{ secrets.FTP_PORT }}
          server-dir: '/home/hpqjihel/public_html/staging.techfordevelopment.com/'
